AUDIO_ENABLE     = no  # Audio output
BACKLIGHT_ENABLE = yes # Enable keyboard backlight functionality
BOOTMAGIC_ENABLE = yes # Enable Bootmagic Lite
COMMAND_ENABLE   = no  # Commands for debug and configuration
CONSOLE_ENABLE   = no  # Console for debug
EXTRAKEY_ENABLE  = yes # Audio control and System control
MOUSEKEY_ENABLE  = no  # Mouse keys
NKRO_ENABLE      = no  # Enable N-Key Rollover
RGBLIGHT_ENABLE  = yes # Enable keyboard RGB underglow
